
[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

[scrolling]
history = 100000

[general]
import = [
    "~/.config/alacritty/keybindings.toml",
]
