[keyboard]
bindings = [
   { key = "Comma", mods = "Command", command = { program = "sh", args = ["-c","open ~/.config/alacritty/alacritty.toml"] } },
    { key = "N", mods = "Command", action = "SpawnNewInstance" }
]

